displayName: Traefik Rybbit Feeder

import: github.com/foxxmd/traefik-rybbit-feeder
type: middleware

summary: A Traefik plugin that feeds Rybbit Analytics with pageview events
iconPath: .assets/icon.png

testData:
  Host: "localhost:3000"
  ApiKey: "1234"
  Websites:
    localhost: siteId
