http:
  middlewares:
    rybbit:
      plugin:
        rybbit-feeder:
          debug: true
          host: https://rybbit.mysite.com
          apiKey: rb_a0938f333a88239c6250c2c3707a
          websites:
            "localhost": "1"
          batchSize: 1
